import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark, neobrutalism, shadesOfPurple } from "@clerk/themes";
import { Toaster } from "sonner";

const inter=Inter({subsets:["latin"]});

export const metadata = {
  title: "Your AI Mentor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
      <ClerkProvider appearance={{
        baseTheme: [neobrutalism],
        signIn: {
          baseTheme: [shadesOfPurple],
        },
      }}>
             <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
          
          {/* header */}
          <Header/>
          <main className="min-h-screen">
          {children}
          </main>
          <Toaster richColors/>
            {/* footer */}
            <footer className="bg-muted/40 py-11">
            <div className="container mx-auto px-4 text-center text-gray-200">
              <p>Made by Piyush</p>
            </div>
            </footer>
          </ThemeProvider>
          </ClerkProvider>
      </body>
    </html>
  );
}
